lib/rom/sql/support/rails_log_subscriber.rb

Now ROM logs are indented in the same way as ActiveRecord

Fixed rails logger indentation

---

lib/rom/sql/relation_inclusion.rb

Removes unused code and improves the situation described in rom-rb/rom#109.

Don't unnecessarily load header

---

Gemfile
lib/rom/sql.rb
lib/rom/sql/commands.rb
lib/rom/sql/relation.rb
lib/rom/sql/relation_inclusion.rb
rom-sql.gemspec
spec/spec_helper.rb
spec/unit/one_to_many_spec.rb

This changes `RelationInclusion` to a `Relation` subclass which makes it work with new way of setting up ROM
refs rom-rb/rom#133

Make it work with subclass-based setup

---

lib/rom/sql/commands.rb
lib/rom/sql/commands/create.rb
lib/rom/sql/commands/delete.rb
lib/rom/sql/commands/update.rb
lib/rom/sql/commands_ext/postgres.rb
spec/integration/commands/update_spec.rb
spec/unit/commands_spec.rb

This adds a way to pass in an original tuple to update command and it will skip the update if nothing was changed:
``` ruby
users.try { update(:by_id, 1).change(name: 'Jane').to(name: 'Jane Doe') }
```
As a bonus it adds pg-specific update which uses `returning` :)

Dirty attributes update

---

lib/rom/sql/commands/create.rb
lib/rom/sql/commands/delete.rb
lib/rom/sql/commands/transaction.rb
lib/rom/sql/commands/update.rb
lib/rom/sql/relation.rb
spec/integration/commands/create_spec.rb
spec/integration/commands/delete_spec.rb
spec/integration/commands/update_spec.rb
spec/unit/migration_tasks_spec.rb

Basic transaction interface on top of commands. All options for Sequel transactions works: http://sequel.jeremyevans.net/rdoc/files/doc/transactions_rdoc.html
Example:
```ruby
users = rom.commands.users
users.create.transaction do
users.create.call(...)
end
users.create.transaction do
users.create.call(...)
tags.create.transaction do
tars.craete.call(...)
end
end
users.create.transaction do
users.create.call(...)
raise Sequel::Rollback
end
users.create.transaction(rollback: :reraise) do
users.create.call(...)
raise Sequel::Rollback
end
```

Basic transaction interface for commands

---

lib/rom/sql/relation.rb
lib/rom/sql/relation/class_methods.rb

With changes merged from rom-rb/rom#158, `rom` now provides an internal API to access an inflector implementation.  This change updates `rom-sql` to use that API and removes any dependency on the `inflecto` gem.

Use internal ROM interface for inflector

---

Gemfile
lib/rom/sql/migration.rb
lib/rom/sql/migration/migrator.rb
lib/rom/sql/migration/template.rb
lib/rom/sql/repository.rb
lib/rom/sql/tasks/migration_tasks.rake
spec/fixtures/migrations/20150403090603_create_carrots.rb
spec/integration/repository_spec.rb
spec/shared/database_setup.rb
spec/spec_helper.rb
spec/unit/migration_spec.rb
spec/unit/migration_tasks_spec.rb
spec/unit/migrator_spec.rb

This makes it possible to inject a migrator to repository which exposes
migration DSL and interface required for running migrations.
This means that the only thing we need to do to use migrations is to
simply setup a repository which removes the `load_setup` task
requirement.

[WIP] Add Migrator repository plugin

---

Gemfile
lib/rom/sql.rb
lib/rom/sql/relation/associations.rb
spec/unit/association_errors_spec.rb

raise a more descriptive error when accessing a non-existent association as per https://github.com/rom-rb/rom/issues/173.
depends on https://github.com/rom-rb/rom/pull/210

raise ROM::NoAssociationError when accessing non-existant relations

---

lib/rom/sql/relation/associations.rb
spec/integration/read_spec.rb

Used the name of the dataset (db table) instead of the relation's name,
that can differ from it.
See [rom#218](https://github.com/rom-rb/rom/issues/218)

fixed bug in ROM::SQL::Relation::Associations#graph_join

---

lib/rom/sql/commands/error_wrapper.rb
spec/integration/commands/create_spec.rb

Fixes rom-rb/rom#236
Note: I'm only testing that [] works for one case, this should probably be changed so that we run all error re-raising tests with both ```[]``` and ```call```.

Wrap errors  when calling command with []-syntax

---

lib/rom/sql/relation.rb
spec/unit/relation_spec.rb

Added [Sequel `invert`](http://sequel.jeremyevans.net/rdoc/classes/Sequel/Dataset.html#method-i-invert) to relation operations.
PS. Seems like I cannot push to `rom/rom-sql` directly.

Add `invert` relation operation

---

lib/rom/sql/relation/associations.rb
lib/rom/sql/relation/class_methods.rb
spec/unit/many_to_one_spec.rb

@solnic Thanks for all your hard work. I'm really enjoying using ROM. I've been using it to make a legacy database a little more consistent and I think I may have found a couple of bugs.
I would love it if you could confirm this is a bug or maybe I'm just _not_ using ROM incorrectly?
1. Can't change `many_to_one` relation name.
2. `many_to_one` uses the wrong tables primary key name.

Relation name and join key fixes for :many_to_one

---

lib/rom/sql/gateway.rb
spec/unit/gateway_spec.rb

- Array of extensions is passed onto the connection.
Example Usage:
`ROM.setup(:sql, [‘postgres://localhost/db', extensions: [:pg_enum, :pg_array])`
@solnic how would you suggest testing and documented this?

Add `:extensions` option to Gateway

---

lib/rom/sql/migration.rb
lib/rom/sql/migration/migrator.rb
spec/integration/repository_spec.rb

Using internal Sequel mechanism allow to check if there are pending
migrations:
```
ROM.env.gateways[:default].pending_migrations?
```

Allow to check for pending migrations

---

Gemfile
lib/rom/sql.rb
lib/rom/sql/migration.rb
lib/rom/sql/tasks/migration_tasks.rake
spec/fixtures/migrations/20150403090603_create_carrots.rb
spec/integration/combine_spec.rb
spec/integration/commands/create_spec.rb
spec/integration/commands/delete_spec.rb
spec/integration/commands/update_spec.rb
spec/integration/migration_spec.rb
spec/integration/read_spec.rb
spec/integration/repository_spec.rb
spec/shared/database_setup.rb
spec/spec_helper.rb
spec/support/active_support_notifications_spec.rb
spec/support/rails_log_subscriber_spec.rb
spec/unit/association_errors_spec.rb
spec/unit/combined_associations_spec.rb
spec/unit/gateway_spec.rb
spec/unit/logger_spec.rb
spec/unit/many_to_many_spec.rb
spec/unit/many_to_one_spec.rb
spec/unit/migration_tasks_spec.rb
spec/unit/one_to_many_spec.rb
spec/unit/plugin/pagination_spec.rb
spec/unit/relation_spec.rb
spec/unit/schema_spec.rb

This is an update to bring rom-sql into line with changes in rom-core. 
Travis failure caused by lack of compatible rom-core version.

Cut dependencies on globals and update tests. Depends on rom-rb/rom#327

---

.rspec
Gemfile
lib/rom/sql/commands/create.rb
lib/rom/sql/commands/default_input.rb
lib/rom/sql/commands/update.rb
lib/rom/sql/relation.rb
lib/rom/sql/schema.rb
lib/rom/sql/types.rb
lib/rom/sql/types/pg.rb
rom-sql.gemspec
spec/integration/commands/create_spec.rb
spec/integration/commands/update_spec.rb
spec/spec_helper.rb
spec/unit/relation_spec.rb
spec/unit/types_spec.rb

This adds `schema` DSL to relations:
``` ruby
class Posts < ROM::Relation[:sql]
schema do
attribute :id, Types::Serial
attribute :title, Types::String
attribute :body, Types::Text
attribute :tags, Types::Array
end
end
```
This is awesome because commands can use the schema to create their input handlers:
``` ruby
class CreatePost < ROM::Commands::Create[:sql]
relation :posts
register_as :create
result :one
end
rom.commands[:posts][:create].input # <= dry-data's safe hash
```
Furthermore, we can generate commands automatically in other places, like rom-repository.

Introduce relation schema

---

Gemfile
lib/rom/plugins/relation/sql/auto_combine.rb
lib/rom/plugins/relation/sql/auto_wrap.rb
lib/rom/sql/association.rb
lib/rom/sql/association/many_to_many.rb
lib/rom/sql/association/many_to_one.rb
lib/rom/sql/association/one_to_one.rb
lib/rom/sql/plugin/assoc_macros.rb
lib/rom/sql/qualified_name.rb
lib/rom/sql/schema.rb
rom-sql.gemspec
spec/integration/association/many_to_many_spec.rb
spec/integration/association/many_to_one_spec.rb
spec/integration/association/one_to_many_spec.rb
spec/integration/association/one_to_one_spec.rb
spec/integration/association/one_to_one_through_spec.rb

This leverages new relation name object (https://github.com/rom-rb/rom/pull/347) and also adds qualified identifiers for associations. Now it is possible to use associations when your PK/FK do not follow common naming conventions. I.e. something like `tenants.tenant_id (PK) <= users.tenant_id (FK)` should work fine.
This PR also contains a breaking change for ad hoc combination names in associations (this won't work anymore: https://github.com/rom-rb/rom-repository/blob/master/spec/shared/relations.rb#L58). Now when you write `belongs :sutin` `sutin` means a dataset (table) name, not a relation name. You can add a relation name with `belongs :weird_name, relation: :nice_name`. This should remove the confusion described in https://github.com/rom-rb/rom-sql/issues/67 We add a combination …

Use qualified combination keys

---

lib/rom/sql/association.rb
lib/rom/sql/association/many_to_many.rb
lib/rom/sql/association/many_to_one.rb
lib/rom/sql/plugin/associates.rb
spec/integration/plugins/associates_spec.rb
spec/shared/database_setup.rb
spec/spec_helper.rb

This makes `associates` plugin use defined schema associations and delegate setting FKs. As a bonus commands now support many-to-many where join-tuples are automatically inserted for you.
Passing ad-hoc key options to `associates` macro is now deprecated.

Refactor :associates plugin to use Association API

---

lib/rom/sql/association/one_to_one.rb
spec/unit/association/one_to_many_spec.rb
spec/unit/association/one_to_one_spec.rb

Here's the feature 😉 . This is useful for `hanami-model` integration. 💚

One To One and One To Many #associate

---

lib/rom/sql/association.rb
lib/rom/sql/association/one_to_many.rb
lib/rom/sql/association/one_to_one.rb

Previously, the `OneToMany` association was inheriting from the `OneToOne`. This is mainly a cosmetic change.

Make OneToOne inherit from OneToMany.

---

lib/rom/sql/commands/error_wrapper.rb
lib/rom/sql/errors.rb
spec/integration/commands/create_spec.rb
spec/shared/database_setup.rb

This PR aims to fix two issues:
1. [Sometimes](https://travis-ci.org/hanami/model/jobs/158778577) Sequel raises a `Sequel::ConstraintViolation`, when a database constraint is violated. I can't reproduce this locally (Mac OS), but it happens on CI and in general on Linux.
2. `ROM::Sql::Commands::ErrorWrapper` uses internally `ERROR_MAP` with `#[]`. This is dangerous because in case of non-mapped errors, instead of raising a generic error it raises `nil`, which causes a `TypeError`. I changed it with `#fetch` which falls back to the generic error (`ROM::Sql::Error`).

Safe error wrapper

---

Gemfile
lib/rom/sql/association.rb
lib/rom/sql/association/many_to_many.rb
lib/rom/sql/gateway.rb
lib/rom/sql/migration.rb
lib/rom/sql/migration/migrator.rb
lib/rom/sql/plugin/associates.rb
lib/rom/sql/plugin/pagination.rb
lib/rom/sql/schema/inferrer.rb
rom-sql.gemspec
spec/unit/gateway_spec.rb

Update to use dry-initializer instead of ROM::Options

---

lib/rom/sql/schema/associations_dsl.rb

Rather than merging on top of options and then referencing its initial value for `as`,
we can simply define the default value inside a new `Hash`, and then merge the user
supplied options on top of it.

Merge on to new Hash to simplify logic

---

lib/rom/sql/relation/reading.rb
spec/unit/relation/inner_join_spec.rb

Dataset#join takes four parameters, though the last is not often used.
The actual signature of the method is:
`def join_table(type, table, expr=nil, options=OPTS, &block)`
where expr is the basic set of `on` parameters for the join
conditions, and OPTS is a set of table modifiers.
For docs, see https://github.com/jeremyevans/sequel/blob/master/lib/sequel/dataset/query.rb#L470-L528

Allow all of Sequel::DataSet#join parameters

---

CHANGELOG.md
lib/rom/sql/extensions/postgres/inferrer.rb
lib/rom/sql/extensions/postgres/types.rb
lib/rom/sql/gateway.rb
spec/extensions/postgres/types_spec.rb
spec/integration/schema/inferrer/postgres_spec.rb
spec/unit/gateway_spec.rb

fixes #140 
I think we need a way to cherry-pick Sequel's extensions depending on what data types we found during the schema inference. I'll try to come up with something, but I guess it's gonna be tricky

Add support for inferring PG's hstore

---

lib/rom/sql/extensions/postgres/inferrer.rb
lib/rom/sql/extensions/postgres/types.rb
lib/rom/sql/types.rb
spec/extensions/postgres/types_spec.rb
spec/integration/schema/inferrer/postgres_spec.rb

Closes #141
This PR adds support for more PG [geometric types](https://www.postgresql.org/docs/9.6/static/datatype-geometric.html).
Supported geometric types:
New:

Add support for more PG geometric types

---

CHANGELOG.md
lib/rom/sql/attribute.rb
spec/unit/relation/where_spec.rb

This adds a nice syntax for range checks. Some examples to get the idea:
```ruby
users.where { id.in(1..100) | created_at(((Time.now - 86400)..Time.now)) }
users.where { id.in(1, 2, 3) }
users.where(users[:id].in(1, 2, 3))
```
/cc @solnic

Add ROM::SQL::Attribute#in for range checks

---

lib/rom/sql/plugin/timestamps.rb
spec/shared/notes.rb
spec/unit/plugin/timestamp_spec.rb

When triggered as a part of a command chain, `before` methods are called
with multiple arguments.  The initial implementation of `timestamp` as a
before filter did not take this into account.
```ruby
create_task = rom.commands(:tasks).create_with_user
create_user = rom.commands(:users).create.with(name: "John")
(create_user >> create_task).call(name: "do the dishes")
```
This fixes the filter method to address this case
Fixes #152

Fix the usage of timestamp in command chains

---

lib/rom/sql/group_dsl.rb
spec/unit/relation/group_spec.rb

@solnic any clue why do we have that `.upcase` for the virtual row?

Fix grouping by a function

---

lib/rom/sql/relation/reading.rb
spec/unit/relation/inner_join_spec.rb

Since association carries all info we need for a join it seems reasonable to infer join condition automatically.

Add support for joins by association name

---

lib/rom/sql/relation/reading.rb
spec/unit/relation/inner_join_spec.rb

With this patch, we can call `#inner_join` method with `RelationProxy`
(instance of repository) objects too.
Reference to https://github.com/rom-rb/rom-sql/issues/172

Call inner joins with relation proxy objects too

---

lib/rom/sql/gateway.rb
lib/rom/sql/migration.rb
lib/rom/sql/tasks/migration_tasks.rake
spec/integration/migration_spec.rb

I actually tried several solutions and came up with a transient global variable
used for running migrations exclusively. Other options would much more invasive
from my POV, i.e. mokey-patching Sequel or the global "main" object / top-level
binding. I beleive we'll be able to get rid of this gvar in a while because we'll
have to take migrations loading under our control for things like
auto-migrations and alike.
`current_gateway` is not thread-safe but I don't think we care, running
migrations in threads won't make anyone happy

Remove global Gateway.instance

---

Gemfile
lib/rom/plugins/relation/sql/auto_restrictions.rb
lib/rom/sql/attribute.rb
lib/rom/sql/errors.rb
lib/rom/sql/gateway.rb
lib/rom/sql/migration.rb
lib/rom/sql/migration/inline_runner.rb
lib/rom/sql/migration/migrator.rb
lib/rom/sql/migration/schema_diff.rb
lib/rom/sql/relation.rb
lib/rom/sql/schema/inferrer.rb
spec/integration/auto_migrations/create_table_spec.rb
spec/integration/auto_migrations/errors_spec.rb
spec/integration/auto_migrations/indexes_spec.rb
spec/integration/auto_migrations/managing_columns_spec.rb
spec/integration/auto_migrations/postgres/column_types_spec.rb
spec/spec_helper.rb

This adds support for automatic DB schema migrations based on relation schemas. Target API will look similar to a single simple call `gateway.auto_migrate!(container)`

Adding API for auto-migrations

---

lib/rom/sql/associations/core.rb
lib/rom/sql/associations/many_to_one.rb
lib/rom/sql/attribute.rb
lib/rom/sql/foreign_key.rb
lib/rom/sql/index.rb
lib/rom/sql/migration.rb
lib/rom/sql/migration/inline_runner.rb
lib/rom/sql/migration/migrator.rb
lib/rom/sql/migration/schema_diff.rb
lib/rom/sql/schema.rb
lib/rom/sql/schema/inferrer.rb
lib/rom/sql/types.rb
spec/integration/auto_migrations/foreign_keys_spec.rb
spec/integration/auto_migrations/indexes_spec.rb
spec/integration/plugins/auto_restrictions_spec.rb
spec/integration/relation_schema_spec.rb
spec/integration/schema/inferrer_spec.rb
spec/shared/users_and_tasks.rb
spec/support/helpers.rb

This adds support for managing foreign key constraints within a single gateway. Foreign key list that I added is kind of generic and can be moved later to the core

Managing foreign keys in auto-migrations

---

lib/rom/sql/extensions/mysql/type_builder.rb
spec/integration/schema/inferrer/mysql_spec.rb

In MySQL it's possible to define `tinytext`, `text`, `mediumtext` or
`longtext` column types. `rom-sql` currently only supports `text`
and `mediumtext` attributes. This change ensures that `tinytext` and
`longtext` are also supported and adds tests to validate the behavior
for all text types.
Fixes #183

Add missing support for *text types in MySQL

---

CHANGELOG.md
lib/rom/sql/function.rb
spec/unit/function_spec.rb

This adds support for calling window functions from rom-sql. Technically, we
were able to call them before because Sequel implements their support and this
commit just adds specs for the implementation so that we can guarantee backward
compatibility (though it's generally not an issue with Sequel :). What I added
is a frame clause builder because we don't like passing SQL strings around.
See https://en.wikipedia.org/wiki/Select_(SQL)#Window_function for more details
on window functions.

[WIP] Support for window functions

---

spec/integration/combine_with_spec.rb
spec/shared/articles.rb

Adding a couple of failing specs for some scenarios I'm hitting in the wild.
The first set is a reproduction of a bug that I'm actively seeing.  The second is chasing after syntax for a join; I can remove that commit from this if necessary to keep things focused.

Combine with natural key

---

lib/rom/sql/extensions/postgres/type_builder.rb
lib/rom/sql/extensions/postgres/types/array.rb
lib/rom/sql/extensions/postgres/types/array_types.rb
spec/extensions/postgres/attribute/array_spec.rb

This fixes a problem (but you can also say it adds a new feature 😆) where using pg arrays with custom types would not result in custom types that we have registered to be used as member types. ie `uuid[]` would not use our `Types::PG::UUID` to process array members.

[PG] arrays with member coercions

---

lib/rom/sql/extensions/postgres/types/geometric.rb
spec/extensions/postgres/types_meta_spec.rb

@flash-gordon as we talk yesterday I updated the geometric Types.

[PG] added meta data for geometric types

---

lib/rom/plugins/relation/sql/instrumentation.rb
spec/unit/relation/instrument_spec.rb

This changes instrumentation plugin to be an sql-specific instrumentation. Unfortunately we can't re-use instrumentation from core, simply because in order to log all queries we are forced to hook into `log_connection_yield` which is defined on sequel's database objects (aka db connections). In the context of this method, we do not have access to relations, and I don't think it's possible to provide that, since it's a database object that's shared across all relations.

Refactor instrumentation plugin and enable logging all sql

---

lib/rom/sql/extensions/postgres/commands.rb
spec/integration/commands/create_spec.rb
spec/integration/commands/update_spec.rb

previously, would get an error from postgres when inserting or updating
a relation with an aliased column in the schema:
ROM::SQL::DatabaseError:                                                                           w
PG::UndefinedColumn: ERROR:  column "name" does not exist
LINE 1:    , "active") VALUES ('Joe', 1, true) RETURNING "name", "i...
this is because the returning clause used the final set of column names
from the schema (introduced in 2.1.0) which failed to take into account
that some of those names might be aliases defined within the relation's
schema.

address a bug with postgres RETURNING and alias columns

---

lib/rom/sql/gateway.rb

Sequel.connect supports Hash for the connection params so should rom-sql.
```ruby
require 'rom'
connection_params = {
adapter: 'postgresql',
host: 'myhost',
database: 'development',
user: 'foo',
password: 'bar',
schema_search_path: 'myschema, public'
}
ROM.container(:sql, connection_params)
```
Wasn't sure if I could just remove the to_s (which leads to the problem) without any side-effects so I just added another when Statement.
There is no test at the moment as I wasn't quite sure where to put it but if the change itself is ok and you tell me where it would fit best I'll certainly add one.

Allow hash-params for the connection

---

CHANGELOG.md
lib/rom/sql/projection_dsl.rb
spec/unit/projection_dsl_spec.rb

Fixes #270 
Thanks to @solnic and @flash-gordon for the indications to implement this one.
At the end, we decided to go with `select { f(:count, :id).as(:count), concat(:first_name, :last_name).as(:full_name) }` for brevety

Support for functions with any return type

---

lib/rom/sql/relation/reading.rb
spec/unit/relation/as_hash_spec.rb

Resolves #272 
Add `Relation#as_hash`
@flash-gordon my first iteration was not delegating to `dataset`
```ruby
def as_hash(attribute = primary_key)
to_a.each_with_object({}) do |tuple, result|
result[tuple[attribute]] = tuple
end
end
```
But since is already implemented in `Sequel` I thought it might be a good idea.

Add Relation#as_hash

---

lib/rom/sql/relation/reading.rb

This optimizes SELECT queries to only select the column needed for `pluck`

Optimize `pluck` to select only the column specified in SQL

---

lib/rom/sql/relation/reading.rb
spec/spec_helper.rb
spec/unit/projection_dsl_spec.rb
spec/unit/relation/project_spec.rb
spec/unit/relation/where_spec.rb

This adds support for subqueries in the select part. It will probably work in `where` as well but I need to test it. I'm also not certain about naming.

Add Relation#query

---

lib/rom/sql/projection_dsl.rb
spec/unit/projection_dsl_spec.rb

Since `Sequel::SQL::Function` accepts multiple parameters as the target
function arguments.

Fix `ProjectionDSL#function` arguments accepting

---

CHANGELOG.md
lib/rom/sql/attribute.rb
lib/rom/sql/function.rb
lib/rom/sql/projection_dsl.rb
spec/unit/attribute_spec.rb
spec/unit/function_spec.rb
spec/unit/projection_dsl_spec.rb

Based on https://github.com/rom-rb/rom-sql/pull/282
I reworked the syntax since I actually don't like the way it's implemented in Sequel. Now we have two versions of `#case` when `CASE`:
```ruby
users.select_append { id.case(1 => `'one'`, else: `'something else'`).as(:one_or_else) }
users.select_append { string::case(id.is(1) => 'one', else: 'else').as(:one_or_else) }
```
Note that `else:` is required in both cases (no pun intended) since Sequel enforces it.
I also added simplified syntax for using typed literal values for projections:
```ruby
users.select_append { num.case('one' => int(1), 'two' => int(2), else: int(0)).as(:num_int) }
```
Sorry for the delay I wanted to play with the code a bit.
/cc @wmaciejak

Add support for CASE expressions

---

CHANGELOG.md
lib/rom/sql/dsl.rb
lib/rom/sql/projection_dsl.rb
lib/rom/sql/restriction_dsl.rb
spec/unit/projection_dsl_spec.rb

Allows this fancy syntax:
```ruby
users.select_append { |posts: |
exists(posts.where(posts[:user_id] => id)).as(:has_posts)
}
```

Allow to project EXISTS

---

lib/rom/sql/mapper_compiler.rb

After merging #324 to master, `rom` test suite (once `rom-sql`
dependency was updated to the new master ref) was failing due to a change
introduced by error on reading the attribute alias from the mapper
compiler.

Fix mapper compiler reading attribute alias

---

lib/rom/sql/plugin/pagination.rb
spec/unit/plugin/pagination_spec.rb

This supports rendering the typical text of:
Showing from `<first>` to `<last>` of `<total>` records

Add helpers to get first/last tuple index in page

---

CHANGELOG.md
lib/rom/sql/gateway.rb
lib/rom/sql/relation/reading.rb
spec/unit/gateway_spec.rb
spec/unit/relation/nullify_spec.rb

I noticed there wasn't a simple way to nullify a relation. This functionality is common in Sequel and Rails (`ActiveRecord::Relation#none`). Will make it easier to short circuit any DB interactions when necessary.

Add ROM::SQL::Relation#nullify

---

lib/rom/sql/relation/reading.rb
spec/unit/relation/union_spec.rb

When Sequel performs a union of two datasets, it will alias the resulting union as `t1` by default. As a result, `select_append` anything that required a qualified column will not work after performing a union. 
To fix this, this PR ensures we qualify the schema when performing a union. If relation_a and relation_b are of the `Relation::Name`, then we use that name as the alias. If they are different, we default the alias to `#{relation_a.name}__#{relation_b.name}`. This is not _technically_ required, but IMO makes the relation more easily inspectable/debuggable, and is more resistant to cases when user's manually qualify columns.

Properly qualify relations when in Relation#union

---

lib/rom/sql/extensions/postgres/types/json.rb
spec/extensions/postgres/types_spec.rb

This adds support for writing primitive values to JSON(B) columns. Sequel has recently added support for it. On the rom-sql's side we only need to change the wrapper.
Other values are interpreted as JSONOp as they did before. We could revise this behavior in the next major version, it was added for compatibility with Hanami < 1.0 but I'm not sure if we still need it.

Wrap JSON primitives before passing them to Sequel (fix #327)

---

lib/rom/sql/relation/reading.rb
spec/unit/relation/project_spec.rb
spec/unit/relation/where_spec.rb

Although removing ORDER BY part from a subquery (as rom-sql currently does) may seem innocent, it really isn't and it leads to bugs.
Consider the following query:
```sql
CREATE TABLE users(id INT, name TEXT);
CREATE TABLE tasks(id INT, user_id INT, title TEXT);
INSERT INTO users(id, name) VALUES 
(1, 'Jane'), 
(2, 'Alice'), 
(3, 'John');
INSERT INTO tasks(user_id, title) VALUES 
(1, 'Jane''s task'), 
(2, 'Alice''s task'), 
(3, 'John''s task');
SELECT user_id, title
FROM tasks
WHERE user_id IN (SELECT id FROM users ORDER BY name LIMIT 1)
--  user_id |    title
-- ---------+--------------
--        2 | Alice's task
SELECT user_id, title
FROM tasks
WHERE user_id IN (SELECT id FROM users LIMIT 1);
--  user_id |    title
-- ---------+-------------
--        1 | Jane's task
```
Here, we list …

Don't remove order in subqueries

---

Gemfile
lib/rom/sql/extensions/postgres/types/array.rb
lib/rom/sql/extensions/postgres/types/json.rb
lib/rom/sql/type_extensions.rb
spec/extensions/postgres/types_spec.rb
spec/integration/auto_migrations/postgres/column_types_spec.rb
spec/support/helpers.rb

A few tweaks to make it work. The trick is not to confuse SQL `null` with JSON `null`. If you want to write JSON `null` to an optional JSON(b) column you'll have to use `ROM::SQL::Types::PG::JSONNull`. Other cases will work just fine.

Support new dry-types

---

README.md
bin/run-specs

running the `docker-compose` command is tedious for testing. This PR adds a `bin/run-specs` helper with the same interface as rspec, but runs specs in the docker containers.

Add bin/run-specs helper for easier testing in development

---

CHANGELOG.md
lib/rom/sql/associations/core.rb
lib/rom/sql/attribute.rb
lib/rom/sql/attribute_aliasing.rb
lib/rom/sql/attribute_wrapping.rb
lib/rom/sql/function.rb
lib/rom/sql/mapper_compiler.rb
lib/rom/sql/relation/reading.rb
spec/integration/wrap_spec.rb
spec/unit/attribute_spec.rb

Previously, when wrapping a relation, the view for the association would not be honored. This would make the output of `.wrap` different from combine, and cause unexpected behavior.
This PR addresses that by first applying the view to the association target if there is one. 
Also, since `.wrap` with prefix attributes, any previously aliased attributes would fail loudly since `Sequel::SQL::AliasedExpression` does not respond to `.as`. To fix this, we now will handle alias `Sequel::SQL::AliasedExpression` by constructing a new instance with the new alias name.

Honor association views when wrapping

---

README.md

The `rom-sql` path does not exists anymore, this commit updates the link to rom-rb.org to `sql`

User documentation link returns a 404

---

lib/rom/sql/relation/reading.rb
spec/unit/relation/join_dsl_spec.rb

Fixes rom-rb/rom-sql#369
When `relation#join` is given a relation with an aliased dataset and a block it should use the relations dataset name instead of the relations name.

relation#join block dsl should use dataset name not alias

---

lib/rom/sql/function.rb
lib/rom/sql/projection_dsl.rb
lib/rom/sql/type_extensions.rb

This PR fixes a few YARD annotations to match current code.
This PR came when I had some warnings:
```
Building YARD (yri) index for rom-sql-3.2.0...
lib/rom/sql/function.rb:189: [UnknownParam] @param tag has unknown parameter name: Conditions. Did you mean `condition`?
lib/rom/sql/function.rb:214: [UnknownParam] @param tag has unknown parameter name: A
lib/rom/sql/projection_dsl.rb:34: [UnknownParam] @param tag has unknown parameter name: attr. Did you mean `attrs`?
lib/rom/sql/type_extensions.rb:12: [UnknownParam] @param tag has unknown parameter name: wrapped
```

(doc) Adjust YARD annotations

---

lib/rom/sql/attribute.rb
lib/rom/sql/attribute_aliasing.rb
lib/rom/sql/extensions/postgres/commands.rb
lib/rom/sql/function.rb
lib/rom/sql/relation.rb
lib/rom/sql/schema.rb
spec/unit/relation/inner_join_spec.rb
spec/unit/relation/order_spec.rb

Fixes #370
Aliased attributes are context based and should default to the
defined dataset name when using them in most queries.
This fix prevents attributes from being aliased during finalization
and provides a way to tell attributes they will be used in a
context where their configured alias should override the default
attribute name.
(Note: after review and before the pull request is accepted, ping me and I'll squash these commits)

Add qualifed projections to schemas & update `dataset#select` calls

---

docsite/source/index.html.md

While reading the [rom-sql docs](https://rom-rb.org/learn/sql/3.2/), I 
found it interesting that the recommended versions were so old.
I've updated these to the latest version bands, and have also modified
the required ruby version to match the gem.

Update versions recommended in the docs

---

lib/rom/sql/associations/many_to_many.rb

In rom master schemas now verify if their attributes are unique, this broke one of the specs here which revelead that ManyToMany would try to project left-side relation columns without taking into consideration that one of the columns may already exist in the schema. The fix was to simply ensure that the schema is unique before projecting.

Ensure ManyToMany produces a unique schema for the left-side relation

---

docsite/source/attributes.html.md

`int` would throw:
```
undefined local variable or method `int' for #<ROM::SQL::ProjectionDSL:0x00007fd68d3d4850>
```
I looked at the source and saw that this should be `integer`.

Change `int` to `integer`

---

Gemfile
docsite/source/advanced-pg-support.html.md
lib/rom/plugins/relation/sql/postgres/streaming.rb
lib/rom/sql/extensions/postgres.rb
lib/rom/sql/gateway.rb
spec/integration/plugins/pg_streaming_spec.rb
spec/unit/gateway_spec.rb

This PR wraps the `sequel_pg`'s streaming functionality up in a neat little bow. We have a maintain a patch that adds this and have been using it in prod for quite awhile. Figured it was time to release it to the world!

Add `:pg_streaming` extension to support streaming tuples

---

lib/rom/sql/function.rb
spec/unit/function_spec.rb
spec/unit/relation/select_append_spec.rb

Fix function qualification methods

---

docsite/source/joins.html.md

Website guide does not match with the documentation and behavior for https://api.rom-rb.org/rom-sql/ROM/SQL/Relation/Reading.html#join-instance_method on the order of columns in the conditions hash.

Fixes column order for ROM::SQL::Relation::Reading #join

---

lib/rom/plugins/relation/sql/postgres/streaming.rb
spec/integration/plugins/pg_streaming_spec.rb

This patch makes streaming for composite relations by applying the `right` side to each streamed tuple of the `left`.

Add support for streaming composite relations

---

lib/rom/sql/function.rb
lib/rom/sql/relation/reading.rb
spec/unit/relation/group_spec.rb
spec/unit/relation/project_spec.rb

Uses Sequel's built-in unordered to remove the order clause from queries.
Today I was trying to do this query:
```ruby
select { [integer::count(id).as(:count), user_id, project_id] }.group_and_count(:project_id, :user_id)
```
But I was told I could not do that:
```
[30] pry(#<TicketsRelation>)> select { [integer::count(id).as(:count), user_id, project_id] }.group_and_count(:project_id, :user_id).to_a
ROM[postgres] (0.8ms)  SELECT "project_id", "user_id", count(*) AS "count" FROM "tickets" GROUP BY "project_id", "user_id" ORDER BY "tickets"."id"
Sequel::DatabaseError: PG::GroupingError: ERROR:  column "tickets.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...ickets" GROUP BY "project_id", "user_id" ORDER BY "tickets"....
```
This is because datasets are …

Add Relation#unordered

---

lib/rom/sql/extensions/postgres/commands.rb
spec/integration/commands/upsert_spec.rb

This PR adds support for inferring partial unique indices in Postgres upserts by allowing the user to set index predicates (as in `ON CONFLICT (...) WHERE <INDEX_PREDICATE>`) on Upsert commands.
Resolves #394

Allow setting index predicate for upserts w/ partial unique indices

---

docsite/source/associations.html.md

`assoc` is for querying association data from a relation, but `combine` is for loading associations within the context of the main relation.
Suggesting this because I feel the existing heading seemed to match what I was looking for, but the text/code underneath it didn't. Maybe I'm getting my terms/ideas mixed up though?

Updating association docs to mention `combine`.

---

docsite/source/migrations.html.md
lib/rom/sql/tasks/migration_tasks.rake
spec/unit/migration_tasks_spec.rb

Hey,
I want to use the default rake migration tasks, but need to customize the table opt. This PR would fix my need.
thanks and best regards

Add migration_options to be able to use the default rake migration tasks with custom opts.

---

.github/workflows/ci.yml

This is causing #419 to fail because every version of dry-transformer
depends on Ruby >= 3.0.0
Co-authored-by: Steven Chudley <steven.chudley@gmail.com>

Remove Ruby 2.7 from CI matrix

---

changelog.yml
lib/rom/sql/projection_dsl.rb
lib/rom/sql/restriction_dsl.rb
spec/unit/projection_dsl_spec.rb
spec/unit/restriction_dsl_spec.rb

We had unit tests before but it wasn't enough, I've stumbled upon it recently.

Fix using filter with block in function syntax

---

lib/rom/plugins/relation/sql/instrumentation.rb
spec/unit/relation/instrument_spec.rb

It happens when there's more than one container using the same gateway. This issue is already fixed in the main branch, I'll add the spec there, though

Fix excessive logging by instrumentation plugin

---

lib/rom/sql/relation/reading.rb

Very small fix to the docs, which defined an overload for a wrong function.

Fix docs for left and right join
