rom-rb/rom-sql

.travis.yml
The same as https://github.com/rom-rb/rom-rails/pull/11
=> speed up builds on Travis

.travis.yml, README.md, Rakefile, lib/rom/sql.rb, lib/rom/sql/repository.rb, spec/shared/database_setup.rb, spec/unit/repository_spec.rb, spec/unit/schema_spec.rb
Use ROM.register_adapter from rom-rb/rom#120
=> Update rom-sql to use latest ROM changes

lib/rom/sql/commands.rb, lib/rom/sql/commands/create.rb, lib/rom/sql/commands/delete.rb, lib/rom/sql/commands/update.rb, lib/rom/sql/commands_ext/postgres.rb, spec/unit/commands_spec.rb
Do not call DB again after data was inserted to DB, use returning function from Sequel to get them for free.
=> #116 - Do not call db to read data after insert.

lib/rom/sql/relation.rb, spec/integration/read_spec.rb
Trying to get my head around how this would work with ROM.
I wrote an integration spec to show what kind of things I'm trying to do.
What do you think?
=> Implement `group by` and friends

lib/rom/sql/plugin/pagination.rb, spec/unit/plugin/pagination_spec.rb
This makes the pager api drop-in compatible with the view code used by Kaminari
=> alias a limit_value method

README.md, lib/rom/sql/plugin/pagination.rb, spec/unit/plugin/pagination_spec.rb
Hello, 
I detected what I believe is a behavioral error at ``Paginator::total_pages``. Correct me if I'm wrong.
=> Fix Paginator::total_pages behavior

CHANGELOG.md
couldn't push or edit via the GUI, so PR it is =)
=> Update CHANGELOG [ci skip]

README.md
Hi, Piotr!
After playing with the README example, I've added small fixes to make it exactly reproducible
=> Add fixes to README example

lib/rom/sql/commands/create.rb, lib/rom/sql/commands_ext/postgres.rb, lib/rom/sql/relation.rb, spec/integration/commands/create_spec.rb
This will enable the use of multi_insert whenever the create command receives an array of tuples
=> Multi insert in create command

lib/rom/sql.rb, lib/rom/sql/error.rb, lib/rom/sql/errors.rb, lib/rom/sql/plugins.rb
Cleaning up `lib/rom/sql.rb` by extracting parts of the file.
=>  refine lib/rom/sql.rb

lib/rom/sql/relation/reading.rb, spec/unit/relation_spec.rb
I added ability to make a unions on relations
=> Add `union` method for relations

spec/integration/commands/create_spec.rb, spec/shared/database_setup.rb, spec/unit/relation_spec.rb
Fixed some small issues while running tests on my local machine under `postgres` localized in Russian.
=> Specs fixed

lib/rom/sql/relation/reading.rb, spec/unit/relation_spec.rb
for exmple:
```
ROM.env.relation(:users).sum(:age) # => 20
```
Return number (similar to count) not relation as other functions.
=> Extend ROM by Aggregation function - SUM

lib/rom/sql/association/many_to_many.rb, lib/rom/sql/association/one_to_one_through.rb, lib/rom/sql/schema.rb, spec/integration/association/many_to_many_spec.rb, spec/integration/association/one_to_one_through_spec.rb, spec/shared/database_setup.rb, spec/shared/users_and_accounts.rb, spec/unit/schema_spec.rb
=> Add support for one-to-one-through-association

.travis.yml, lib/rom/sql/schema/inferrer.rb, spec/integration/schema_spec.rb
This does not support multicolumn foreign key but I bet this is a really rare beast.
=> Infer foreign keys

.travis.yml, circle.yml, lib/rom/sql/commands.rb, lib/rom/sql/commands/postgres.rb, lib/rom/sql/commands_ext/postgres.rb, lib/rom/sql/relation/writing.rb, rom-sql.gemspec, spec/integration/commands/create_spec.rb, spec/integration/commands/upsert_spec.rb, spec/shared/database_setup.rb, spec/spec_helper.rb
=> Add upsert option for insert call. Only works for PostgreSQL >=9.5

spec/integration/association/many_to_many_spec.rb, spec/integration/association/one_to_one_spec.rb, spec/integration/combine_spec.rb, spec/integration/commands/create_spec.rb, spec/integration/commands/delete_spec.rb, spec/integration/commands/update_spec.rb, spec/integration/commands/upsert_spec.rb, spec/integration/gateway_spec.rb, spec/integration/migration_spec.rb, spec/integration/read_spec.rb, spec/integration/schema_inference_spec.rb, spec/integration/setup_spec.rb, spec/integration/support/active_support_notifications_spec.rb, spec/integration/support/rails_log_subscriber_spec.rb, spec/shared/database_setup.rb, spec/spec_helper.rb, spec/unit/association_errors_spec.rb, spec/unit/gateway_spec.rb, spec/unit/logger_spec.rb, spec/unit/migration_tasks_spec.rb, spec/unit/migrator_spec.rb, spec/unit/plugin/assoc_macros/combined_associations_spec.rb, spec/unit/plugin/assoc_macros/many_to_many_spec.rb, spec/unit/plugin/assoc_macros/many_to_one_spec.rb, spec/unit/plugin/assoc_macros/one_to_many_spec.rb, spec/unit/relation_spec.rb, spec/unit/schema_spec.rb, spec/unit/types_spec.rb
I'm going to add ability to cherry-pick certain DB specs via an env variable
=> Run specs against all DBs

Gemfile, lib/rom/sql/extensions/postgres/types.rb, lib/rom/sql/schema/inferrer.rb, lib/rom/sql/types.rb, spec/extensions/postgres/inferrer_spec.rb, spec/extensions/postgres/integration_spec.rb, spec/integration/schema_inference_spec.rb
See https://github.com/rom-rb/rom-sql/issues/88
=> Make inferrer to use non-strict types

lib/rom/sql/extensions/postgres/types.rb, lib/rom/sql/gateway.rb, lib/rom/sql/schema/inferrer.rb, spec/spec_helper.rb, spec/unit/gateway_spec.rb
Fixes one failure in https://github.com/hanami/model/tree/new-engine
=> Load db-extensions in gateway

lib/rom/sql/relation/reading.rb, spec/unit/relation/read_spec.rb
refs hanami/model#345
refs hanami/model#354
=> Add Relation#read(sql_str)

lib/rom/sql/association.rb, lib/rom/sql/association/many_to_many.rb, lib/rom/sql/association/many_to_one.rb, lib/rom/sql/association/one_to_many.rb, spec/integration/association/many_to_many/custom_fks_spec.rb, spec/integration/association/many_to_one/custom_fks_spec.rb, spec/integration/association/one_to_many/custom_fks_spec.rb
=> Add support for setting custom FKs in associations

Gemfile, lib/rom/sql/plugin/associates.rb
=> Refactor associates plugin to use hooks

lib/rom/sql/association.rb, lib/rom/sql/association/many_to_many.rb, lib/rom/sql/association/many_to_one.rb, lib/rom/sql/association/one_to_many.rb, spec/integration/association/many_to_many/from_view_spec.rb, spec/integration/association/many_to_one/from_view_spec.rb, spec/integration/association/one_to_many/from_view_spec.rb
=> Add support for custom views in has_many

lib/rom/sql/gateway.rb, lib/rom/sql/transaction.rb, spec/integration/gateway_spec.rb
Now we don't need to expose the connection object for that.
=> Add ROM::SQL::Gateway#transaction

.travis.yml, CHANGELOG.md, Gemfile, circle.yml, lib/rom/sql/commands/create.rb, lib/rom/sql/commands/update.rb, lib/rom/sql/extensions.rb, lib/rom/sql/extensions/mysql.rb, lib/rom/sql/extensions/mysql/inferrer.rb, lib/rom/sql/extensions/postgres/commands.rb, lib/rom/sql/extensions/postgres/inferrer.rb, lib/rom/sql/extensions/postgres/types.rb, lib/rom/sql/extensions/sqlite.rb, lib/rom/sql/extensions/sqlite/inferrer.rb, lib/rom/sql/schema/inferrer.rb, lib/rom/sql/types.rb, spec/extensions/postgres/inferrer_spec.rb, spec/extensions/postgres/types_spec.rb, spec/integration/schema/inferrer/mysql_spec.rb, spec/integration/schema/inferrer/postgres_spec.rb, spec/integration/schema/inferrer/sqlite_spec.rb, spec/integration/schema/inferrer_spec.rb, spec/integration/schema_inference_spec.rb
Closes https://github.com/rom-rb/rom-sql/issues/129
=> Add missing PG types with auto-inference

CHANGELOG.md, lib/rom/sql/extensions/sqlite.rb, lib/rom/sql/extensions/sqlite/inferrer.rb, lib/rom/sql/extensions/sqlite/types.rb, rom-sql.gemspec, spec/extensions/sqlite/types_spec.rb, spec/integration/schema/inferrer/sqlite_spec.rb, spec/spec_helper.rb
=> Add Types::SQL::SQLite::Object for columns without a type affinity

lib/rom/sql/schema/inferrer.rb, spec/integration/commands/create_spec.rb, spec/integration/commands/upsert_spec.rb, spec/integration/schema/inferrer_spec.rb, spec/shared/users_and_tasks.rb
@solnic I put index names to a set under `:indexes` key.
=> Infer indexes and associate types with them

Gemfile, lib/rom/plugins/relation/sql/instrumentation.rb, lib/rom/sql/plugins.rb, lib/rom/sql/relation/reading.rb, spec/unit/relation/instrument_spec.rb
=> Add :instrumentation relation plugin

lib/rom/sql/attribute.rb, lib/rom/sql/relation/reading.rb, spec/unit/relation/where_spec.rb
=> Coerce condition values for restrictions

lib/rom/plugins/relation/sql/auto_restrictions.rb, lib/rom/sql/plugins.rb, spec/integration/plugins/auto_restrictions_spec.rb
=> Add :auto_restrictions plugin

CHANGELOG.md, Gemfile, lib/rom/sql/attribute.rb, lib/rom/sql/extensions/postgres/types.rb, rom-sql.gemspec, spec/extensions/postgres/attribute_spec.rb
@solnic wdyt? If it looks fine overall I'll add more operations.
=> Support for type extensions in Query and Projection DSLs

lib/rom/sql/schema/inferrer.rb, spec/integration/schema/inferrer_spec.rb, spec/shared/users.rb, spec/shared/users_and_tasks.rb
=> Add inferring the length constraint for char types

lib/rom/sql/association.rb, lib/rom/sql/association/many_to_one.rb, lib/rom/sql/association/name.rb, lib/rom/sql/association/one_to_many.rb, lib/rom/sql/attribute.rb, lib/rom/sql/function.rb, lib/rom/sql/projection_dsl.rb, lib/rom/sql/relation.rb, lib/rom/sql/relation/reading.rb, spec/integration/association/many_to_many/custom_fks_spec.rb, spec/integration/association/many_to_many/from_view_spec.rb, spec/integration/association/many_to_many_spec.rb, spec/integration/association/many_to_one/custom_fks_spec.rb, spec/integration/association/many_to_one/from_view_spec.rb, spec/integration/association/many_to_one/self_ref_spec.rb, spec/integration/association/many_to_one_spec.rb, spec/integration/association/one_to_many/custom_fks_spec.rb, spec/integration/association/one_to_many/from_view_spec.rb, spec/integration/association/one_to_many/self_ref_spec.rb, spec/integration/association/one_to_many_spec.rb, spec/integration/commands/upsert_spec.rb, spec/integration/plugins/auto_wrap_spec.rb, spec/integration/sequel_api_spec.rb, spec/unit/function_spec.rb, spec/unit/order_dsl_spec.rb, spec/unit/relation/dataset_spec.rb, spec/unit/relation/project_spec.rb, spec/unit/relation/qualified_columns_spec.rb, spec/unit/relation/where_spec.rb, spec/unit/restriction_dsl_spec.rb
@solnic this requires a thorough look. We definitely have a leaking abstraction regarding qualified SQL names
=> Fix Sequel warnings

lib/rom/plugins/relation/sql/auto_restrictions.rb, lib/rom/sql/attribute.rb, lib/rom/sql/index.rb, lib/rom/sql/migration/inline_runner.rb, lib/rom/sql/migration/schema_diff.rb, lib/rom/sql/relation.rb, lib/rom/sql/schema.rb, lib/rom/sql/schema/dsl.rb, lib/rom/sql/schema/index_dsl.rb, lib/rom/sql/schema/inferrer.rb, spec/integration/auto_migrations/indexes_spec.rb, spec/integration/plugins/auto_restrictions_spec.rb, spec/integration/relation_schema_spec.rb, spec/integration/schema/inferrer_spec.rb, spec/support/helpers.rb, spec/unit/types_spec.rb
That should be a good start :)
=> Add DSL for defining indexes

lib/rom/sql/migration.rb, lib/rom/sql/migration/inline_runner.rb, lib/rom/sql/migration/migrator.rb, lib/rom/sql/migration/recorder.rb, lib/rom/sql/migration/runner.rb, lib/rom/sql/migration/schema_diff.rb, lib/rom/sql/migration/writer.rb, spec/integration/auto_migrations/file_based_migrations_spec.rb, spec/integration/auto_migrations/foreign_keys_spec.rb, spec/integration/auto_migrations/indexes_spec.rb, spec/integration/auto_migrations/managing_columns_spec.rb, spec/integration/auto_migrations/postgres/column_types_spec.rb
=> Create migration files in auto-migrations

lib/rom/sql/relation/writing.rb, spec/extensions/postgres/attribute_spec.rb, spec/support/test_configuration.rb, spec/unit/relation/import_spec.rb
This method import data from another relation. In common cases, it will use the `INSERT ... SELECT ...` statement which is known as being very effective.
=> Add SQL::Relation#import

lib/rom/sql/function.rb, spec/unit/function_spec.rb
Solves #202 
@flash-gordon added the code and test.
Hope this is what you are looking for 😄
=> infer db type in cast function if not specify

lib/rom/sql/function.rb, lib/rom/sql/projection_dsl.rb, spec/unit/function_spec.rb
=> Add support for the FILTER clause

lib/rom/sql/extensions/postgres/type_builder.rb, lib/rom/sql/extensions/postgres/types/array.rb, lib/rom/sql/extensions/postgres/types/array_types.rb, lib/rom/sql/extensions/postgres/types/ltree.rb, lib/rom/types/values.rb, spec/extensions/postgres/attribute/array_spec.rb, spec/extensions/postgres/attribute_spec.rb, spec/extensions/postgres/types_spec.rb, spec/integration/schema/inferrer/postgres_spec.rb
=> Extract common tree path object

lib/rom/sql/extensions/postgres/commands.rb, spec/unit/commands/create_spec.rb
=> Fix command results when custom schema is used

lib/rom/sql/join_dsl.rb, lib/rom/sql/relation/reading.rb, spec/unit/relation/join_dsl_spec.rb, spec/unit/relation/right_join_spec.rb
It shouldn't even break existing code
=> Add a simple DSL for joining relations

CHANGELOG.md, lib/rom/sql/function.rb, spec/unit/function_spec.rb
Now it can be used with a block
=> Enhance support for the WITHIN GROUP clause

lib/rom/sql/migration.rb, spec/integration/gateway_spec.rb
https://github.com/rom-rb/rom-sql/issues/310
=> Simplify setting up migrator

lib/rom/sql/attribute.rb, lib/rom/sql/function.rb, lib/rom/sql/mapper_compiler.rb, lib/rom/sql/migration/schema_diff.rb, lib/rom/sql/schema/attributes_inferrer.rb, lib/rom/sql/schema/index_dsl.rb, spec/integration/auto_migrations/indexes_spec.rb, spec/integration/auto_migrations/managing_columns_spec.rb, spec/integration/commands/create_spec.rb, spec/integration/commands/update_spec.rb, spec/integration/schema/inferrer/postgres_spec.rb, spec/spec_helper.rb, spec/support/helpers.rb, spec/unit/function_spec.rb
=> Update to work with decoupled alias options

lib/rom/sql/relation/reading.rb, spec/unit/relation/where_spec.rb
=> Fix aliased attributes sql literals

lib/rom/sql/relation/reading.rb, spec/unit/relation/join_dsl_spec.rb
=> Fix join conditions from block when relation is passed

rom-sql.gemspec
See https://github.com/rom-rb/rom/pull/550.
=> Update links on RubyGems.org gem page

lib/rom/sql/gateway.rb, lib/rom/sql/relation.rb, lib/rom/sql/transaction.rb
https://github.com/rom-rb/rom/pull/621
=> Use keywords in transaction methods

docsite/source/advanced-pg-support.html.md
Hey there,
stumbled over this tiny typo while reading the docs about it. Thanks for rom, excellent library!
=> Fix typo in streaming docs for Advanced PG Support
